snc_redis:
    session:
        client: session
        ttl: 1200
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
        session:
            type: predis
            alias: session
            dsn: redis://localhost

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
