version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      SERVER_NAME: ${SERVER_NAME:-http://localhost:80, caddy:80}
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8000}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-4443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-4443}
        protocol: udp

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
